// Expression funtion


// Random price generator with random number of discount;

let price1 = 100;
let price2 = 200;
let price3 = 300;

let discount1 = 0.05;
let discount2 = 0.10;
let discount3 = 0.15;

// Creating expression function

const finalPrice = function()
{
    let randomPrice = eval(`price${Math.floor(Math.random()*3)+1}`);
    let randomDiscount = eval(`discount${Math.floor(Math.random()*3)+1}`);
    console.log(`Random Price generated by code =` +randomPrice);
    console.log(`Random discound generated by code =` +randomDiscount);

    return randomPrice - (randomPrice * randomDiscount);
}

let ans = finalPrice();
console.log(`The final Price is = ` +ans);
