//create a business name generated by combining list of Adjective and shop name and another word. 
//name should be generated randomly picking from the option....

// Adjective...,.......

// Carzy 
// Amezing 
// fire

// Shop Name:

// Engine 
// Food 
// Garments

// Another words........

// Bros 
// limited 
// Hub

let adjective1 = 'Crazy';
let adjective2 = 'Amezing';
let adjective3 = 'fire';

let shopName1 = 'Engine';
let shopName2 = 'Food';
let shopName3 = 'Garments';

let anotherWord = 'Bros';
let anotherWord2 = 'limited';
let anotherWord3 = 'Hub';

function randomBuninessName() 
{
    let randomAdjective = eval(`adjective${Math.floor(Math.random()*3)+1}`);
    let randomShopName = eval(`shopName${Math.floor(Math.random()*3)+1}`);
    let randomAnotherWord = eval(`anotherWord${Math.floor(Math.random()*3)+1}`);

    console.log(randomAdjective);
    console.log(randomShopName);
    console.log(randomAnotherWord);
    return`${randomAdjective} ${randomShopName} ${randomAnotherWord}`;
}

let generatedName = randomBuninessName();
console.log("The combine random Businees name : " + generatedName);